export enum navigateTo {
    DASHBOARD = '/dashboard',
    THANKS_FOR_REGISTRATION = '/thanks-for-registration',
    SIGNIN = '/signin',
    PROFILE_ORDERS = '/profile/orders',
    PROFILE_GENERAL = '/profile/general',
    SIGNUP = '/signup',
    LANDING = '/',
    ORDER_SEARCH = '/order-search',
    FORGOT_PASSWORD = '/forgot-password',
    ORDER = '/order/[orderId]',
    USER = '/user/[userId]',
    PRIVACY_POLICITY = '/privacy-policy',
    USER_AGREEMENT = '/user-agreement',
    VERIFICATION = '/verification',
    FOUNDERS = '/founders',
    PAYOUTS = '/payouts',
}
