import { Dayjs } from 'dayjs';
import { Genders } from './settings';

export type IUser = {
    firstName: string;
    lastName: string;
    email: string;
    dateOfBirth: Dayjs;
    gender: Genders;
    phoneNumber: string;
    avatar?: string;
    completedOrders: number;
    rating?: number;
    id: string;
};

export enum Banks {
    SBER = 'sberbank',
    TINKOFF = 'tinkoff',
    AB_RUSSIA = 'abRussia',
    ABSOLUTE_BANK = 'absoluteBank',
    AVANGARD = 'avangard',
    AUTO_GRAD_BANK = 'autoGradBank',
    AUTO_TORG_BANK = 'autoTorgBank',
    AGRO_PROM_KREDIT = 'agroPromKredit',
    ASIA_PACIFIC_BANK = 'asiaPacificBank',
    AK_BARS_BANK = 'akBarsBank',

    AKB_DERZHAVA = 'akbDerzhava',
    AKB_EUROFINANCE_MOSNARBANK = 'akbEuroFinanceMosNorBank',
    AKB_PRIMORYE = 'akbPrimorye',
    AKB_SLAVIYA = 'akbSlavia',
    AKB_TENDER_BANK = 'akbTenderBank',
    AKB_CENTER_CREDIT = 'akbCenterCredit',
    AKI_BANK = 'akiBank',
    ALEF_BANK = 'alefBank',
    ALMAZ_ERGIEN_BANK = 'almazErgienBank',
    ALFA_BANK = 'alfaBank',

    ARES_BANK = 'aresBank',
    BANK_AVERS = 'bankAvers',
    BANK_AGROROS = 'bankAgroRos',
    BANK_AKCENT = 'bankAkcent',
    BANK_ALECSANDROVSKIY = 'bankAlecsandrovskiy',
    BANK_BBR = 'bankBBR',
    BANK_BKF = 'bankBKF',
    BANK_VBRR = 'bankVBRR',
    BANK_VENEC = 'bankVenec',
    BANK_VOLOGJANIN = 'bankVologjanin',

    BANK_DOM_RF = 'bankDomRF',
    BANK_EKB = 'bankEKB',
    BANK_ZARECHYE = 'bankZarechye',
    BANK_ZENIT = 'bankZenit',
    BANK_INTEZA = 'bankInteza',
    BANK_IPB = 'bankIPB',
    BANK_ITURUP = 'bankITURUP',
    BANK_YOSHCAR_OLA = 'bankYoshcarOla',
    BANK_KAZAN = 'bankRin',
    BANK_KREMLEVSKIY = 'bankKremlevskiy',

    BANK_MBA_MOSKVA = 'bankMBAMoskva',
    BANK_MIR_PRIVELEGIY = 'bankMirPrivelegiy',
    BANK_MOSKVA_CITY = 'bankMoskvaCity',
    BANK_OBYEDINENNIY_CAPITAL = 'bankObyedinenniyCapital',
    BANK_ORENBURG = 'bankOrenburg',
    BANK_PSKB = 'bankPSKB',
    BANK_RAZVITIE_STOLICA = 'bankRazvitieStolica',
    BANK_ROUND = 'bankRound',
    BANK_RUSSKIY_STANDART = 'bankRusskiyStandart',
    BANK_SARATOV = 'bankSaratov',

    BANK_SGB = 'bankSGB',
    BANK_SIAB = 'bankSIAB',
    BANK_SINARA = 'bankSinara',
    BANK_SNEJINSKIY = 'bankSnejinskiy',
    BANK_SOUZ = 'bankSouz',
    BANK_URALSIB = 'bankUralSib',
    BANK_FINSERVIS = 'bankFinServis',
    BANK_CHBRR = 'bankCHBRR',
    BELGOROD_SOTS_BANK = 'belgorodSotsBank',
    BJF_BANK = 'bjfBank',

    BKS_BANK = 'bksBank',
    BLANK_BANK = 'blankBank',
    BRATSKIY_ANKB = 'bratskiyANKB',
    BISTRO_BANK = 'bistroBank',
    WILDBERRIES_BANK = 'wildBerriesBank',
    VLAD_BUISNESS_BANK = 'vladBuisnessBank',
    VNESH_FIN_BANK = 'vneshFinBank',
    VTB = 'vtb',
    VUZ_BANK = 'vuzBank',
    GAZPROM_BANK = 'gazpromBank',

    GAZTRANS_BANK = 'gaztransBank',
    GAZENERGO_BANK = 'gazenergoBank',
    GRANT_INVEST_BANK = 'grantInvestBank',
    GEN_BANK = 'genBank',
    GOR_BANK = 'gorBank',
    GUTA_BANK = 'gutaBank',
    DALNEVOSTOCHNIY_BANK = 'dalnevostochniyBank',
    DATA_BANK = 'dataBank',
    DJEY_AND_TI_BANK = 'djeyAndTiBank',
    DOLINSK = 'dolinsk',

    DRIVE_KLIK_BANK = 'driveKlikBank',
    ENISEYSKIY_OBYEDINENNIY_BANK = 'eniseyskiyObyedinenniyBank',
    ZEMSKIY_BANK = 'zemskiyBank',
    ZOLOTAYA_KORONA = 'zolotayaKorona',
    IK_BANK = 'ikBank',
    IN_BANK = 'inBank',
    ISHBANK = 'ishBank',
    KB_BAIKAL_KREDO_BANK = 'kbBaikalKredoBank',
    KB_IS_BANK = 'kbIsBank',
    KB_NOVIY_VEK = 'kbNoviyVek',

    KB_POYDEM = 'kbPoydem',
    KB_ROST_FINANS = 'kbRostFinans',
    KB_SOLIDARNOST = 'kbSolidarnost',
    KB_STROY_LES_BANK = 'kbStroyLesBank',
    KB_HLINOV = 'kbHlinov',
    KB_UNISTRIM = 'kbUnistrim',
    KIWI_BANK = 'kiwiBank',
    KOSHELEV_BANK = 'koshelevBank',
    KREDIT_EUROPA_BANK = 'kreditEuropaBank',
    KREDIT_URAL_BANK = 'kreditUralBank',

    KROKUS_BANK = 'krokusBank',
    KUBAN_KREDIT = 'kubanKredit',
    KUBAN_TORG_BANK = 'kubanTorgBank',
    KUZNEC_BUISNESS_BANK = 'kuznecBuisnessBank',
    LANTA_BANK = 'lantaBank',
    LEVOBEREJNIY = 'levoberejniy',
    LOKO_BANK = 'lokoBank',
    METALL_INVEST_BANK = 'metalInvestBank',
    MEJDUNARODNIY_FINANSOVIY_KLUB = 'mejdunarodniyFinansoviyKlub',
    MET_KOM_BANK = 'metKomBank',
    MI_N_BANK = 'miNBank',

    MIR_BISNESS_BANK = 'mirBisnessBank',
    MKB = 'MKB',
    MODUL_BANK = 'modulBank',
    MONETA = 'moneta',
    MORSKOY_BANK = 'morskoyBank',
    MOS_KOM_BANK = 'mosKomBank',
    MOS_KOMMERTC_BANK = 'mosKommertcBank',
    MOS_OBL_BANK = 'mosOblBank',
    MS_BANK_RUS = 'msBankRus',
    MSP_BANK = 'mspBank',

    MTS_BANK = 'mtsBank',
    NATS_INVEST_PROM_BANK = 'natsInvestPromBank',
    NATSIONALNIY_STANDART = 'natsionalniyStandart',
    NBD_BANK = 'nbdBank',
    NIKO_BANK = 'nikoBank',
    NK_BANK = 'nkBank',
    NKO_MOBI_DENGI = 'nkoMobiDengi',
    NKO_U_MANI = 'nkoUMani',
    NOVIKOM_BAK = 'novikomBank',
    NOVO_BANK = 'novoBank',

    NOKSS_BANK = 'nokssBank',
    NORVIK_BANK = 'norvikBank',
    NR_BANK = 'nrBank',
    NS_BANK = 'nsBank',
    OZON_EKOM_BANK = 'ozonEkomBank',
    OTKRITIE = 'otkritie',
    OTP_BANK = 'otpBank',
    PERVIY_DOR_TRANS_BANK = 'perviyDorTransBank',
    PERVIY_INVESTICIONNIY_BANK = 'perviyInvesticionniyBank',
    POCHTA_BANK = 'pochtaBank',

    PRIM_SOTC_BANK = 'primSotcBank',
    PRIO_VNESH_TORG_BANK = 'prioVneshTorgBank',
    PRO_BANK = 'proBank',
    PROM_SVYAZ_BANK = 'promSvyazBank',
    PROM_TRANS_BANK = 'promTransBank',
    RAYFFAYZEN_BANK = 'rayffayzenBank',
    REALIST_BANK = 'realistBank',
    RENESSANS_KREDIT = 'renessansKredit',
    RECO_KREDIT = 'recoKredit',
    RN_BANK = 'rnBank',

    RNKB_BANK = 'rnkbBank',
    RNKO_DENGI_MAIL_RU = 'rnkoDengiMailRu',
    ROS_BANK = 'rosBank',
    ROS_DOR_BANK = 'rosDorBank',
    ROS_SELHOZ_BANK = 'rosSelhozBank',
    ROYAL_KREDIT_BANK = 'royalKreditBank',
    RUS_NAR_BANK = 'rusNarBank',
    RUS_UNIVERSAL_BANK = 'rusUniversalBank',
    SANKT_PETERBURG = 'sanktPeterburg',
    SDM_BANK = 'sdmBank',

    SEVERNIY_NARODNIY_BANK = 'severniyNarodniyBank',
    SIB_SOTC_BANK = 'sibSotcBank',
    SINKO_BANK = 'sinkoBank',
    SITY_BANK = 'sityBank',
    SMP_BANK = 'smpBank',
    SNGB = 'sngb',
    SOVKOM_BANK = 'sovkomBank',
    SOLID_BANK = 'solidBank',
    SOTCIUM_BANK = 'sotciumBank',
    TAVRICHESKIY_BANK = 'tavricheskiyBank',

    TAT_SOTC_BANK = 'tatSotcBank',
    TIMER_BANK = 'timerBank',
    TOIOTA_BANK = 'toiotaBank',
    TOLYATTI_HIM_BANK = 'tolyattiHimBank',
    TOMSK_PROM_STROY_BANK = 'tomskPromStroyBank',
    TOCHKA_FK_OTKRITIE = 'tochkaFkOtkritie',
    TRANS_KAPITAL_BANK = 'transKapitalBank',
    TRANS_STROY_BANK = 'transStroyBank',
    UBR_I_R = 'ubrIR',
    UGLE_MET_BANK = 'ugleMetBank',

    URAL_FD = 'uralFD',
    URAL_PROM_BANK = 'uralPromBank',
    URAL_FINANS = 'uralFinans',
    FINAM = 'finam',
    FORA_BANK = 'foraBank',
    FORSHTAD = 'forshtad',
    FRIDOM_FINANS = 'fridomFinans',
    HAYS = 'hays',
    HAKASSKIY_MUNITSIPALNIY_BANK = 'hakasskiyMunitsipalniyBank',
    HOUM_KREDIT_BANK = 'houmKreditBank',

    CENTER_INVEST = 'centerInvest',
    CHELIND_BANK = 'chelindBank',
    CHELYAB_INVEST_BANK = 'chelyabInvestBank',
    EKONOM_BANK = 'economBank',
    EKSPO_BANK = 'ekspoBank',
    ELITA = 'elita',
    ELPLAT = 'elplat',
    ENERGO_BANK = 'energoBank',
    ENERGO_TRANS_BANK = 'energoTransBank',
    ES_BI_AI_BANK = 'esBiAiBank',

    UG_INVEST_BANK = 'ugInvestBank',
    UNIKREDIT_BANK = 'unikreditBank',
    YANDEX_BANK = 'yandexBank',
}
